### ISSUE TITLE
Number of container don't match expected number

### ISSUE THREAD

**Issue by Belphemur** [Wowu/docker-rollout#10]
Hello,

Hard issue to explain, but easy to reproduce.

I have two containers. One frontend and one backend.

The backend is already configured to be scaled at 2 containers.
The frontend is configured to be scaled at 1 container.

When I do rollout on the backend container, everything is peachy, it works as expected (4 containers then 2 containers).
When I do rollout on the frontend container after the backend one, one of the backend container gets deleted.

I wonder why it is happening ...

**Comment by Wowu** [comment]
Hi, is the number of containers configured in `docker-compose.yml`, or using `--scale` flag?

**Comment by Belphemur** [comment]
hoo, I see, it's the one setup using the `--scale` arg.
I imagine I should switch with setting it up in the docker-compose file.

**Comment by Belphemur** [comment]
Confirmed, having `deploy.replicas` settings fixes everything :)

**Comment by Wowu** [comment]
@Belphemur Great, thanks for sharing your solution 😃
