### ISSUE TITLE
remove SC2086 check as it is not very helpful and should be human decided (as you noticed)

### ISSUE THREAD

**Issue by Morriz** [Wowu/docker-rollout#24]
Just my 2 cents

**Comment by Wowu** [comment]
Thanks for the suggestion. I really like this check despite the verbosity of ignore comments, as it prevented many errors related to word splitting, at least for me. 

I think adding ignore comments with en explanation makes the script somewhat more maintainable, and ensures we quote variables in every place we should.

**Comment by Morriz** [comment]
when it needs more comments than quotes something is wrong imo ;)
