### ISSUE TITLE
How to deploy to remote instance

### ISSUE THREAD

**Issue by fliespl** [Wowu/docker-rollout#6]
My deploy command:

```
docker-compose -H "ssh://owadmin@${DEPLOY_HOST}" --profile app -f docker-compose.yml -f docker-compose.deploy.yml -f docker-compose.${BUILD_ENV}.yml up -d --remove-orphans
```

Is it possible to do it here? (-H option).

**Comment by Wowu** [comment]
Setting the `DOCKER_HOST` environment variable should work.

**Comment by Wowu** [comment]
Same thing goes for `--profile` flag, use `COMPOSE_PROFILES` env instead.

https://docs.docker.com/compose/environment-variables/envvars/#compose_profiles

**Comment by fliespl** [comment]
Thank you - will give it a try :) (probably gonna conflict with gitlab ci which also utilizes this variable).

**Comment by Wowu** [comment]
You can do it this way to avoid the conflict:

```bash
env DOCKER_HOST="ssh://owadmin@${DEPLOY_HOST}" docker-compose -f docker-compose.yml ...
```
